### ISSUE TITLE
var vs tensor error in nb

### ISSUE THREAD

**Issue by Benudek** [keitakurita/Practical_NLP_in_PyTorch#2]
;-)

attn(q, k, v)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-28-ce7bb9fa8c06> in <module>
----> 1 attn(q, k, v)

/opt/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

<ipython-input-25-b945a4707a2a> in forward(self, q, k, v, mask)
     28         attn = attn / attn.sum(dim=-1, keepdim=True)
     29         attn = self.dropout(attn)
---> 30         output = torch.bmm(attn, v) # (Batch, Seq, Feature)
     31         log_size(output, "attention output size") # (Batch, Seq, Seq)
     32         return output

RuntimeError: bmm(): argument 'mat2' (position 1) must be Variable, not torch.FloatTensor

—

attn_head = AttentionHead(20, 20)
attn_head(q, k, v)

TypeError: torch.mm received an invalid combination of arguments - got (torch.FloatTensor, Variable), but expected one of:
 * (torch.FloatTensor source, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (torch.FloatTensor, !Variable!)
 * (torch.SparseFloatTensor source, torch.FloatTensor mat2)
      didn't match because some of the arguments have invalid types: (!torch.FloatTensor!, !Variable!)

**Comment by keitakurita** [comment]
Hi, sorry but I'm not supporting PyTorch versions lower than 1.0, do you mind upgrading? Thanks.

**Comment by Benudek** [comment]
thx for the hint ! of course would ugrade!
